### ISSUE TITLE
App crashes when trying to open the chat pane

### ISSUE THREAD

**Issue by w2isto** [reorproject/reor#12] opened 2024-01-29 18:12 UTC
The app crashes when trying to open the chat pane.

ggml_metal_init: allocating
ggml_metal_init: found device: Apple M2
ggml_metal_init: picking default device: Apple M2
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: error: could not use bundle path to find ggml-metal.metal, falling back to trying cwd
ggml_metal_init: loading 'ggml-metal.metal'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=260 "Tiedostoa ”ggml-metal.metal” ei voitu avata, koska kyseistä tiedostoa ei ole olemassa." UserInfo={NSFilePath=ggml-metal.metal, NSUnderlyingError=0x1180f085b40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
llama_new_context_with_model: failed to initialize Metal backend
zsh: segmentation fault  ./Reor

**Comment by samlhuillier** [comment] 2024-01-30 16:05
Hey thanks so much for making this issue! Managed to reproduce it and turns out it was to do with some of the metal executables from llamacpp not being packaged with the executable. Should be fixed in the [new release](https://github.com/reorproject/reor/releases/tag/v0.1.37)...Please let me know this fixes it on your end :)

**Comment by w2isto** [comment] 2024-01-30 16:48
Thanks for being so quick on fixing it. Now it works perfectly!

**Closed** 2024-02-16 11:17 UTC
