### ISSUE TITLE
Model doesn't have knowledge about my notes.

### ISSUE THREAD

**Issue by shaikhalid** [reorproject/reor#51] opened 2024-02-16 20:05 UTC
Do I have to download any specific model? Because I tried with a bunch of different models and none of them seem to have access to my knowledge base

**Comment by samlhuillier** [comment] 2024-02-16 22:38
I'd suggest trying the largest model you can run on your machine. Some of the standard models I recommend are [phi-2](https://huggingface.co/TheBloke/phi-2-GGUF/blob/main/phi-2.Q4_K_M.gguf) Llama 7b or 13b and mistral MOE. 

Also, what are you asking? And what kind of things do you have in your notes?

**Comment by shaikhalid** [comment] 2024-02-17 02:04
I tried with Llama2 7b 4bit model and even Mistral MOE but they replied out of context.

I have 2 To Do list of tasks. I am asking something like "Are there any important tasks on my To Do list?"

**Comment by arnwas** [comment] 2024-02-17 09:56
I hda the same impression and found the error message i posted in #54 maybe same reason here?

**Comment by shiloh92** [comment] 2024-02-17 12:17
This is interesting; I have tried another RAG git and it also could not index my notes. Reor seems to do the same, I have tried all 3 options for embeddings, changed RAG quantity drop down, and tried several Mistral models, Phi-2 but none of them seem to have a clue about any of the notes. I have added hashtags to my notes in hopes of triggering some sort of indexing. I don't think any has occurred as semantic search also doesn't pick up any references in any of my 4 notes.

**Comment by decisivedevops** [comment] 2024-02-17 12:36
> This is interesting; I have tried another RAG git and it also could not index my notes. Reor seems to do the same, I have tried all 3 options for embeddings, changed RAG quantity drop down, and tried several Mistral models, Phi-2 but none of them seem to have a clue about any of the notes. I have added hashtags to my notes in hopes of triggering some sort of indexing. I don't think any has occurred as semantic search also doesn't pick up any references in any of my 4 notes.

similar experience myself. tried three embeddings and several models but no indexing of the notes.

**Comment by samlhuillier** [comment] 2024-02-17 12:40
What happens when you search for something? Do items show up with a similarity percentage?
Also if you open a note, do other notes show up on the sidebar? Could someone share a screenshot of what they see?

**Comment by samlhuillier** [comment] 2024-02-17 13:02
Interesting. Is there anything that shows up in the web console? If you hit option-cmd-i 
Particularly interested in if anything shows up when you boot the app, does it say "initializing" vector database?

**Comment by samlhuillier** [comment] 2024-02-17 13:06
Also, would you be able to run it from source?
Like this:
```
git clone https://github.com/reorproject/reor
cd reor
npm install
npm run dev
```
And report what you see in the terminal logs

**Comment by decisivedevops** [comment] 2024-02-17 13:07
> Interesting. Is there anything that shows up in the web console? If you hit option-cmd-i Particularly interested in if anything shows up when you boot the app, does it say "initializing" vector database?

when I open any notes, these show up in console.

![CleanShot 2024-02-17 at 18 36 27](https://github.com/reorproject/reor/assets/95153836/6ffbcbdb-17f9-48fe-8c04-d00a98893837)

**Comment by decisivedevops** [comment] 2024-02-17 13:07
> Also, would you be able to run it from source? Like this:
> 
> ```
> git clone https://github.com/reorproject/reor
> cd reor
> npm install
> npm run dev
> ```
> 
> And report what you see in the terminal logs

checking this.

**Comment by decisivedevops** [comment] 2024-02-17 13:17
![CleanShot 2024-02-17 at 18 46 26](https://github.com/reorproject/reor/assets/95153836/62c29e29-b0c6-4d12-9cae-043ad86838f4)
![CleanShot 2024-02-17 at 18 47 18](https://github.com/reorproject/reor/assets/95153836/9a7504f7-c0f1-4f91-81a8-e7d558729c4c)

reached here.

**Comment by samlhuillier** [comment] 2024-02-17 13:19
Is there anything you see in the terminal as well when running from source?

**Comment by decisivedevops** [comment] 2024-02-17 13:20
![CleanShot 2024-02-17 at 18 49 50](https://github.com/reorproject/reor/assets/95153836/53b38678-77ed-4f8f-abfa-469655413b32)


just this.

**Comment by samlhuillier** [comment] 2024-02-17 13:56
Which node version are you using? If you are not using latest (20.11.1_ could you upgrade to that?
I suspect this is the cause: https://github.com/vitejs/vite/issues/14299

**Comment by decisivedevops** [comment] 2024-02-17 16:10
> …/reor on main
> node --version
v21.6.2


---


![CleanShot 2024-02-17 at 21 40 00@2x](https://github.com/reorproject/reor/assets/95153836/94380561-8450-495a-a082-4b573f62ff8e)

**Comment by samlhuillier** [comment] 2024-02-17 20:27
Fix is released: https://github.com/reorproject/reor/releases/tag/v0.1.46
Could you folks download it and confirm that it works?

**Comment by decisivedevops** [comment] 2024-02-18 07:56
> Fix is released: https://github.com/reorproject/reor/releases/tag/v0.1.46 Could you folks download it and confirm that it works?

i can see related notes and chat answers also are in the notes context. thanks.

---
i am using mistral model that might be reason UI seems bit slow. trying with smaller models.

**Comment by samlhuillier** [comment] 2024-02-18 10:42
Great - I suggest trying something like [phi-2](https://huggingface.co/TheBloke/phi-2-GGUF/blob/main/phi-2.Q4_K_M.gguf)

**Comment by shaikhalid** [comment] 2024-02-18 19:36
I think its working after the latest release

**Comment by samlhuillier** [comment] 2024-02-18 19:37
Amazing I shall close the issue then

**Closed by samlhuillier** 2024-02-18 19:37 UTC
